# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cherkaoui/DELIVERY/R-Type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cherkaoui/DELIVERY/R-Type

# Include any dependencies generated for this target.
include CMakeFiles/R_Type.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/R_Type.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/R_Type.dir/flags.make

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o: src/client/source/lib/Map.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Map.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Map.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Map.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o: src/client/source/lib/Menu.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Menu.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Menu.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Menu.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o: src/client/source/lib/Connection.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Connection.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Connection.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Connection.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o: src/client/source/lib/CreateRoom.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/CreateRoom.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/CreateRoom.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/CreateRoom.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o: src/client/source/lib/Room.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Room.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Room.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Room.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o: src/client/source/lib/JoinRoom.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/JoinRoom.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/JoinRoom.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/JoinRoom.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o: src/client/source/lib/Auth.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Auth.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Auth.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Auth.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o: src/client/source/lib/Game.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Game.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Game.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Game.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o: src/client/source/lib/Starship.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Starship.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Starship.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Starship.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o: src/client/source/lib/Animation.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Animation.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Animation.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Animation.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o: src/client/source/lib/Bullet.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Bullet.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Bullet.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Bullet.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o: src/client/source/lib/Mob.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Mob.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Mob.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/Mob.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o


CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o: src/client/source/lib/utils.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_13) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/utils.cpp

CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/utils.cpp > CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.i

CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/lib/utils.cpp -o CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.s

CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o


CMakeFiles/R_Type.dir/src/client/source/main.cpp.o: CMakeFiles/R_Type.dir/flags.make
CMakeFiles/R_Type.dir/src/client/source/main.cpp.o: src/client/source/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_14) "Building CXX object CMakeFiles/R_Type.dir/src/client/source/main.cpp.o"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/R_Type.dir/src/client/source/main.cpp.o -c /home/cherkaoui/DELIVERY/R-Type/src/client/source/main.cpp

CMakeFiles/R_Type.dir/src/client/source/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/R_Type.dir/src/client/source/main.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/cherkaoui/DELIVERY/R-Type/src/client/source/main.cpp > CMakeFiles/R_Type.dir/src/client/source/main.cpp.i

CMakeFiles/R_Type.dir/src/client/source/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/R_Type.dir/src/client/source/main.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/cherkaoui/DELIVERY/R-Type/src/client/source/main.cpp -o CMakeFiles/R_Type.dir/src/client/source/main.cpp.s

CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.requires:

.PHONY : CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.requires

CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.provides: CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.requires
	$(MAKE) -f CMakeFiles/R_Type.dir/build.make CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.provides.build
.PHONY : CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.provides

CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.provides.build: CMakeFiles/R_Type.dir/src/client/source/main.cpp.o


# Object files for target R_Type
R_Type_OBJECTS = \
"CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o" \
"CMakeFiles/R_Type.dir/src/client/source/main.cpp.o"

# External object files for target R_Type
R_Type_EXTERNAL_OBJECTS =

R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o
R_Type: CMakeFiles/R_Type.dir/src/client/source/main.cpp.o
R_Type: CMakeFiles/R_Type.dir/build.make
R_Type: CMakeFiles/R_Type.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/cherkaoui/DELIVERY/R-Type/CMakeFiles --progress-num=$(CMAKE_PROGRESS_15) "Linking CXX executable R_Type"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/R_Type.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/R_Type.dir/build: R_Type

.PHONY : CMakeFiles/R_Type.dir/build

CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Map.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Menu.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Connection.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/CreateRoom.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Room.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/JoinRoom.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Auth.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Game.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Starship.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Animation.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Bullet.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/Mob.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/lib/utils.cpp.o.requires
CMakeFiles/R_Type.dir/requires: CMakeFiles/R_Type.dir/src/client/source/main.cpp.o.requires

.PHONY : CMakeFiles/R_Type.dir/requires

CMakeFiles/R_Type.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/R_Type.dir/cmake_clean.cmake
.PHONY : CMakeFiles/R_Type.dir/clean

CMakeFiles/R_Type.dir/depend:
	cd /home/cherkaoui/DELIVERY/R-Type && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/cherkaoui/DELIVERY/R-Type /home/cherkaoui/DELIVERY/R-Type /home/cherkaoui/DELIVERY/R-Type /home/cherkaoui/DELIVERY/R-Type /home/cherkaoui/DELIVERY/R-Type/CMakeFiles/R_Type.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/R_Type.dir/depend

