# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile CXX with /usr/bin/c++
CXX_FLAGS = -g3 -Wall -O0   -std=gnu++14

CXX_DEFINES = 

CXX_INCLUDES = -I/home/cherkaoui/DELIVERY/R-Type/src/client/source/includes -I/home/cherkaoui/DELIVERY/R-Type/src/client/source/lib -I/home/cherkaoui/DELIVERY/R-Type/src/server/includes 

